<?php

// Returns a tree structure with children grouped by parent_id
function tree(array $items, int $parent_id = 0, int $level = 1) : array {
    $branch = [];
    foreach ($items as $item) {
        if ($item->getParent() == $parent_id) {
            $node = [
                'by' => $item->getBy() ?? 'unknown',
                'time' => $item->getTime(),
                'text' => $item->getText() ?? '',
                'level' => $level
            ];
            $children = tree($items, $item->getId(), $level + 1);
            if ($children) {
                $node['children'] = $children;
            }
            $branch[] = $node;
        }
    }
    return $branch;
}

// Flatten a tree generated by the tree function
function flatten(array $tree) : array {
    $result = [];
    foreach ($tree as $node) {
        $children = $node['children'] ?? false;
        if ($children) {
            unset($node['children']);
            $result[] = $node;
            $result = array_merge($result, flatten($children));
        } else {
            $result[] = $node;
        }
    }
    return $result;
}
